### ISSUE TITLE
Integration issues

### ISSUE THREAD

**Issue by Azbesciak** [devforth/painterro#104]
Hello,
first of all - nice project.
I would like to pass my own color select control/method... somehow. This should be possible at least to some scope via pure js (replace via removing control and putting my own, but what then...? Need to integrate it somehow, how?)
Thanks

**Comment by ivictbor** [comment]
@Azbesciak I think instead of removing control you should just fork and extend it with some callback, returning something from callback hides default dialog for example. Then you just need expose api which sets color

**Comment by Azbesciak** [comment]
Ok, thank you.
