### ISSUE TITLE
image cache

### ISSUE THREAD

**Issue by arigus** [devforth/painterro#110]
how remove image cache, reopened image is not saved (it is cached).
thanks

**Comment by ivictbor** [comment]
@arigus could you please post painterro settings?

**Comment by arigus** [comment]
settings? 
   Painterro({
       hiddenTools:'open',
       saveHandler: function (image, done) {
           var formData = new FormData();
           formData.append('file', image.asBlob(), <?php echo json_encode($file) ?>);
           // you can also pass suggested filename
           // formData.append('image', image.asBlob(), image.suggestedFileName());
           var xhr = new XMLHttpRequest();
           xhr.open('POST', "<?php echo base_url();?>homework/imageDownload/?>", true);
           xhr.onload = xhr.onerror = function () {
               done(true);	
               window.close();
           };
           xhr.send(formData);

       },

**Comment by ivictbor** [comment]
@arigus hmm, still can't reproduce your issue, could you please quickly record a simple video or write detailed description? Also please specify which version do you use?

**Comment by arigus** [comment]
opened from URL/image and saved and exit fro paintero. then again try to open from that URL/image in to paintero - image comes from cache. checked URL/image was changed.

**Comment by ivictbor** [comment]
@arigus noone from team was able to understand an issue, without video we can't help here.

Also probablhy it is not painterro issue. When loading image add some random get argument e.g. "domain/image.png?anticache=12312hjg1h2j3gj"
