### ISSUE TITLE
Show inside a container <div>

### ISSUE THREAD

**Issue by LukeTOBrien** [devforth/painterro#111]
Hello there,

How do I show Painterro inside a `<div>`.  
More specificly for my case I am creating a WebComponent library with [LitElement](https://lit-element.polymer-project.org/) so I want Painterro to appear inside the `shadowRoot`, something like:

```js
firstUpdated() {
       Painterro().show({
           container: this.shadowRoot
       });
    }
```

Thanks

**Comment by ivictbor** [comment]
@LukeTOBrien use "id" option according to a doc

**Comment by LukeTOBrien** [comment]
Oh yes, silly of me to have missed https://github.com/devforth/painterro#configuration (first option).  
I guess this does a `querySelector`? So fo a `shadowRoot` this wouldn't find the element.

I will do some playing, thanks!

**Comment by LukeTOBrien** [comment]
In [LitElement we can set the render root](https://lit-element.polymer-project.org/guide/templates#renderroot), so that what I've done and it works as expected:

```typescript
@customElement('my-element')
export class MyElement extends LitElement {

    constructor() {
        super();
    }

    createRenderRoot() {
        return this;
      }

    firstUpdated() {
       Painterro({
           id: "painterro"
       }).show();
    }

    render() {
        return html`<div id="painterro"></div>`;
    }

}
```
