### ISSUE TITLE
Undo button not show in toolbar - How can i Show it ?

### ISSUE THREAD

**Issue by thinhcnb297** [devforth/painterro#119]

**Comment by ivictbor** [comment]
@thinhcnb297 ease post code which opens painterro and a screenshot

**Comment by bobslee** [comment]
I experience the same issue with release **1.2.18**. 

See screenshot below, not visible:
- undo
- settings (cog)

Simple code:
```
Painterro({
    id: "someId", 
    saveHandler: function (image, done) { ...}
});
```

![image](https://user-images.githubusercontent.com/328803/106719894-1a78ee00-6603-11eb-8ae6-5d269a302554.png)

**Comment by ivictbor** [comment]
@bobslee I see that it is not `1.2.18` version, it looks more like `0.x.x`

Please check fiddle with the latest version https://jsfiddle.net/vanbrosh/wnebj4h7 , it uses the latest release https://github.com/devforth/painterro/releases/tag/v1.2.20

The question is :
1. how did you install your 1.2.18
2. Why did you made a conclusion you are using 1.2.18?

This might help me to understand

**Comment by bobslee** [comment]
@ivictbor thanks for answering!
I hope you can give us a clue where to get the right version from. Thanks!

I just checked and it's indeed version `0.2.21`.

This seems however packaged into the `1.2.18` release, I downloaded from https://github.com/devforth/painterro/archive/v1.2.18.tar.gz
Which only has a minified (js) file in `painterro-1.2.18/wp/tags/0.2.21/trunk/painterro-0.2.21.min.js`
The archive only shows `painterro-1.2.18/wp/tags/0.2.21.x`

See screenshot below...
No minified files found in GitHub release either, as opossed to your latest fine `1.2.20` release.

By the way, why the distribution it's directory name contains `wp` ?
Has anything to do with Wordpress? I use your library in a different stack / webapp. 

![image](https://user-images.githubusercontent.com/328803/106747913-cda60f00-6624-11eb-8e41-9ff61584c803.png)

**Comment by bobslee** [comment]
@ivictbor Of course, from now on I will use your latest release `>=v1.2.20`.

**Comment by ivictbor** [comment]
Ohh, I understood what happened finally.

1. Why github release had no minified file attached: I had a bug in release script which broke an attachment upload for several last releases , fixed in 20
2. Why you found 0.x.x - it was in project sources because we have wp plugin , should fix also or remove sources

**Comment by bobslee** [comment]
@ivictbor awesome, thanks for the explanation.
I shall test the new release very soon.

So the only (static asset) requirement to import in a HTML Doc, is the minified JS file shipped with a release?

**Comment by ivictbor** [comment]
Yes, only 1 min.js file, as mentioned in readme.
In most cases you will never need other files shipped in release (map ans sources are very optional)

**Comment by ivictbor** [comment]
Closing, solved
