### ISSUE TITLE
Multiple Painterro support?

### ISSUE THREAD

**Issue by bobslee** [devforth/painterro#121]
Are multiple Painterro objects in a HTML document supported?
Apparently when uploading/opening an image in some Painterro object it replaces the image in another Painterro object.

See the example in JSFiddle https://jsfiddle.net/3trq1apd/

**Comment by ivictbor** [comment]
@bobslee fixed in 1.2.29+, here is how to use it: https://hinty.io/devforth/multiple-painterro-instances-on-one-page/

**Comment by bobslee** [comment]
@ivictbor I tested and works perfect. Thanks!
Also thanks for the information to solve the styling (positioning) issues!

**Comment by ivictbor** [comment]
Great. Pleasure to help, and thabk you for the issue!
