### ISSUE TITLE
[Feature request] Pencil drawing tool

### ISSUE THREAD

**Issue by bobslee** [devforth/painterro#122]
Would be great if there's a free drawing tool.

**Comment by ivictbor** [comment]
It is brush, or what do you mean by free?

**Comment by ivictbor** [comment]
Any example on existinge solution?

**Comment by bobslee** [comment]
@ivictbor sorry for misunderstanding. I meant a pencil tool.

Example from wPaint (http site): http://wpaint.websanova.com/

![image](https://user-images.githubusercontent.com/328803/107261112-333c3600-6a3f-11eb-8181-d09592e3f95f.png)

**Comment by ivictbor** [comment]
Yes, exactly, but what is the difference between the pencil and brush from computer graphics point of view? 

I thought about it from the beginning of painterro, but did not find anything in pencil which could not be satisfied with brush - you can set any thickness on brush, any color. Maybe including the fact that brush can have blurred edges (anyway our brush does not have it for now, easy to add btw) so it might make sense to replace brush icon with pencil icon in painterro?

**Comment by bobslee** [comment]
Indeed @ivictbor. Sorry, I totally misted the brush tool.
I wasn't used to the icon and didn't tried that one yet. I regret.
The brush icon now makes sense! Thanks!
