### ISSUE TITLE
Text applying controls move when zooming

### ISSUE THREAD

**Issue by cdiazedgar** [devforth/painterro#124]
Hello! thanks for working on this amazing project!!.
I noticed this behaviour, when you apply text on a zoomed image, the controls for apply/cancel text move, let me show you:
![1](https://user-images.githubusercontent.com/31668603/107853430-af39d380-6ddb-11eb-90f1-e995068e187e.png)
![2](https://user-images.githubusercontent.com/31668603/107853433-b52fb480-6ddb-11eb-8f9f-1ee849b9dcd0.png)
![3](https://user-images.githubusercontent.com/31668603/107853434-b6f97800-6ddb-11eb-91e2-b114131a9153.png)
![4](https://user-images.githubusercontent.com/31668603/107853435-b95bd200-6ddb-11eb-9cc2-5b6e37e1b4c7.png)

I find it troublesome because when the zoom is too much, the controls simply vanish from screen, is there a way to leave them fixed on the toolbar?

*btw, I noticed that they are bound to the scrollbars, if  I activate the text input, then zoom , moving the scrollbars repositions the apply/cancel controls beside the textbox, however, this also makes the text move when applied

Hope you can chek it out, and thanks again!

**Comment by cdiazedgar** [comment]
Here's what I mean by  bound to the scrollbars
![sc2](https://user-images.githubusercontent.com/31668603/107853864-eb6e3380-6ddd-11eb-9a74-cd935890419c.png)
![sc3](https://user-images.githubusercontent.com/31668603/107853869-f032e780-6ddd-11eb-9b2c-296376f6b47f.png)

Again, the problem comes when the zoom is too much that the controls simply vanish.
Thank you!

**Comment by ivictbor** [comment]
@cdiazedgar thanks a lot! 
Great issue description. Able to reproduce. And definitely will work on it soon

**Comment by ivictbor** [comment]
@cdiazedgar fixed, explanation https://drive.google.com/file/d/1D0vlic7Z52Ao4Xzvl4cSW4ZL1nncmmFo/view

**Comment by cdiazedgar** [comment]
Awesome!! you rock!! thank you very much, I'll check it right away :)

**Comment by cdiazedgar** [comment]
Sorry I didn't reply sooner, it works like a charm! Thank you very much!!
