### ISSUE TITLE
[Feature Request]  zoom in mobile

### ISSUE THREAD

**Issue by cdiazedgar** [devforth/painterro#125]
Hi there, amazing work! I was wondering if there is a way to zoom in mobile devices? I've been trying it my tablet and is amazing! But sometimes I need to zoom but haven't found the way, is it possible?

Thank you very much for working on this Amazing tool!

**Comment by ivictbor** [comment]
@cdiazedgar thanks for the request. We wanted to implement this using 2 buttons on zoom panel, this is also requested in the issue : https://github.com/devforth/painterro/issues/20

Will it work?

**Comment by Darktimeoff** [comment]
fixed in 1.2.36 version

**Comment by cdiazedgar** [comment]
Thanks!! I'll Check it out! You're Awesome!

**Comment by ivictbor** [comment]
I am closing the issue now, don't hesitate to reopen if any issues
