### ISSUE TITLE
TypeError Cannot set property ctrlKey of #<TouchEvent> which has only a getter

### ISSUE THREAD

**Issue by halimb** [devforth/painterro#127]
**Describe the bug**
in `js/main.js`  the `touchmove(e)` function is trying to set a readonly event property https://github.com/devforth/painterro/blob/786a5a3699bbc42ff3cd2235d547559e317c10da/js/main.js#L918  

Moreover, in the same function, the condition in the `if` statement:
https://github.com/devforth/painterro/blob/786a5a3699bbc42ff3cd2235d547559e317c10da/js/main.js#L916

is the same as the one in the `else if` :
https://github.com/devforth/painterro/blob/786a5a3699bbc42ff3cd2235d547559e317c10da/js/main.js#L920

The `else if` will never be executed.
 
**Painterro version**
v1.2.36

**Comment by ivictbor** [comment]
👋 Halim, thanks a lot , we will check it

**Comment by ivictbor** [comment]
@halimb I made a fix in `1.2.53` feel free to ask any questions
