### ISSUE TITLE
[Bug] how_to_paste_actions IS NOT WORKING in last version

### ISSUE THREAD

**Issue by losbit** [devforth/painterro#128]
This code is preventing Painterro from loading, so it is impossible to use.

![image](https://user-images.githubusercontent.com/45804465/112709329-91559900-8e86-11eb-9d57-e1451d1c4613.png)

**Comment by ivictbor** [comment]
Hi @losbit thanks for the bug report, we will take a look ASAP

**Comment by ivictbor** [comment]
Don't hesitate to reopen if needed

**Comment by losbit** [comment]
Problem continue happening:
![image](https://user-images.githubusercontent.com/45804465/115826236-30ab7480-a3d0-11eb-9df2-6ec8885cea3b.png)
Console shows error:
![image](https://user-images.githubusercontent.com/45804465/115826342-5a649b80-a3d0-11eb-9865-b7791ac75ead.png)
Tried in Chrome, Opera and Edge - Windows 10
Set it up in local server - Appserver windows and Linux hosting godaddy
Painterro just do not load

**Comment by ivictbor** [comment]
@losbit thanks, found another bug that I did not reproduce because had elements on the page without id, so the code tried to get the element with undefined ids.

Fixed in 1.2.44:

https://jsfiddle.net/ivictbor/50q7c26h/2/

**Comment by losbit** [comment]
There is another bug:
Whether you paste or open image as soon as painterro has just loaded, it always replace_all, it does not matter the options you set in how_to_paste_actions, But it only happens once painterro's just loaded with using any other tool.

**Comment by losbit** [comment]
![image](https://user-images.githubusercontent.com/45804465/115903850-b3ace900-a429-11eb-9b1d-343d1cdb9652.png)
![image](https://user-images.githubusercontent.com/45804465/115903983-dd661000-a429-11eb-8d55-0a126e401455.png)

**Comment by losbit** [comment]
Notice background resizes to the image size
![image](https://user-images.githubusercontent.com/45804465/115904102-02f31980-a42a-11eb-9553-4a0292de1352.png)

**Comment by ivictbor** [comment]
@losbit this is expected behavior from the beginning, I thought about it at the project design phase and I came to conclusion that most time when user pastes to the empty background he doesnot need to keep original size and empty background.
If you really need this I can create a special painterro option for you which will turn this behaviour to suggest paste dialog on empty painterro.  But please specify your usecase, and ideally create a new issue so I can refer to it.
Thanks in advance.

**Comment by losbit** [comment]
@ivictbor I really appreciate your help in this isssue.
Thank you!
Regards,
Enrique Izarra
