### ISSUE TITLE
Copy Paste does not work when an image is loaded.

### ISSUE THREAD

**Issue by swapsshah** [devforth/painterro#130]
**Describe the bug**
Copy Paste does not work when an image is loaded via Painterro({
                id: "p1",}).show(URL)

**Painterro version**
Was using v1.2.36, then tried latest v1.2.37 and also tried a past release v1.2.30.

**To Reproduce**
1. Load a existing image using Painterro({: "p1",}).show(URL)  [URL of the Image to load]
2. Try to copy paste an external image via Drag-n-Drop or using Ctrl-V
3. The Paste functionality does not work!
4. Exception on Browser Console - 
main.js:1156 Uncaught TypeError: URL.createObjectURL is not a function
    at A.value (main.js:1156)
    at HTMLDocument.drop (main.js:1037)
5. NOTE: However the Copy-Paste functionality works good when we start with an Empty Image/ No pre-loaded Image. Painterro({: "p1",}).show() [When Existing Image is NOT loaded by default]

**Expected behavior**
Copy-Paste functionality should work as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/82358157/114341802-31ded500-9b78-11eb-966c-bddc53a810d5.png)

**Browser**
Google Chrome Version 89.0.4389.114 (Official Build) (64-bit) on Windows 8.1
Same error is reproduced on Firefox and Edge (latest versions).

**Comment by ivictbor** [comment]
Thanks, we are checking

**Comment by ivictbor** [comment]
@swapsshah can't reproduce,
Please provide your  `URL`
And ideally image

**Comment by ivictbor** [comment]
@swapsshah 

I checked it =deeper, and this is the pretty strange issue: URL/createObjectURL is fully browser thing: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

* There might be a lot of things. I need more env details.
Interesting case: in your development page how do you open HTML file with script? Do you use some dev server (with HTTP port opened e.g. 8000 or 8080) or file `.html`? I know the file is a very rare way to develop, but anyway, Chrome does not support `URL.createObjectURL` on locally opened files (BTW a lot of API would not work in such mode): https://stackoverflow.com/a/7284547/3479125

* Also just in case I found the fallback `(window.URL ? URL : webkitURL).createObjectURL(evt.data);` here https://stackoverflow.com/a/10195751/3479125 but I think it is for old browsers because now webkitURL is legacy. And since you mentioned pretty new chrome it is not your case. Also, it would not work for a lot of users because we have it from beginning and it is used in all paste functions.

**Comment by swapsshah** [comment]
Dear Ivan,

Thank you for looking into this. 

We tried v1.2.38 but unfortunately the issue still persists. Here is the snapshot-
![image](https://user-images.githubusercontent.com/82358157/114815762-7c5c8d80-9dd4-11eb-8903-0732f7372632.png)

As mentioned above after saving an Image created using Painterro (on the server); when we load the image again for the user to edit if further (or at a later point in time as a use case). The existing image is loaded correctly (as can be seen in the snapshot), but when I try to COPY-PASTE an Image on top of the loaded Image, we see the exception on the Console (A different one this time, maybe one step up/down on the callstack with the fallback implemented in v1.2.38).

To further check on the issue (just to separate out local DEV environment), we tried the same on a BETA server environment but we get the same result.

WITHOUT this feature of being able to edit an existing image saved on the server it is difficult to integrate Painterro with our product. 

Kindly advice. Thank in advance!

Regards,
Swapneel Shah

**Comment by ivictbor** [comment]
@swapsshah still did not receive URL and image.

Anyway did you try minimal installation before posting an issue to understand whether it is Painterro issue or yours? Anyway, did it for you:
Anyway I did it, please go https://hinty.io/painterro_paste_demo/

1. Open
2. Make PrntScr
3. Ctrl +V
4. answer here whether it works

This is a single HTML file:
```
<html>
  <body>
    <script type="text/javascript" src="https://github.com/devforth/painterro/releases/download/v1.2.38/painterro-1.2.38.min.js"></script>

    <script>
      Painterro().show('https://images.unsplash.com/photo-1618277779512-fbe781205465?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1868&q=80')
    </script>
  </body>
</html>
```

**Comment by swapsshah** [comment]
Dear Ivan @ivictbor,

Thank you for looking into this and doing the Quick demo. Appreciate it!

However, here are two demo samples-
1. https://www.softusvista.com/Painterro_DOES-NOT-WORK.html
Here the Ctrl + V gives the same ERROR as mentioned above.
2. https://www.softusvista.com/Painterro_WORKS.html
Here the Ctrl + V works as expected.

The only difference in both the samples is that in the one where it works the IMAGE URL is given in-line (similar to your Demo) and the one where it does not work the URL is given as a Parameter [As mentioned in my first comment]. 

NOTE: That the Image is loaded correctly in both the cases, which means the path given is same/ correct. Sincere Apologies for not doing the DEMO for your sooner. My bad! 

Attached snapshots here-
DOES NOT WORK-
![image](https://user-images.githubusercontent.com/82358157/114974350-d5ddbe80-9e9f-11eb-979f-c3fc365d3321.png)

WORKS-
![image](https://user-images.githubusercontent.com/82358157/114974382-e726cb00-9e9f-11eb-85c1-04d9e8e625c8.png)

PS: I also tried Incognito modes and other two browsers (Firefox and Edge). Same issue is reproducible.

Regards,
Swapneel Shah

**Comment by ivictbor** [comment]
@swapsshah

As I said you kill `window.URL` by yourself

![image](https://user-images.githubusercontent.com/1838656/114991811-b1371600-9ea2-11eb-8466-a7ee05d0e118.png)

Recommendations:
1. Never use variable names with CAPITAL CASE, you might kill other system objects.
2. Vannila code is not a super good idea, I would recommend using Babel, then you will be able to never to use var and use lets and conts.

**Comment by swapsshah** [comment]
Dear Ivan @ivictbor ,

Aah... My bad again! Silly mistake of mine... Thank you for giving your time on this. Really appreciate it!

Regards,
Swapneel Shah

**Comment by ivictbor** [comment]
@swapsshah you are always welcome!
And good luck with a project!!! You will do it!
