### ISSUE TITLE
Enforce minimum pixelizePixelSize

### ISSUE THREAD

**Issue by appetere** [devforth/painterro#132]
**Describe the bug**

The "Pixelise selected area" tool doesn't _appear_ to do anything when `pixelizePixelSize` is set to **1%**.

For small selections, the canvas image looks the same before and after.  For large selections, the image just looks very slightly blurred.

Also, because the percentage is in user settings, and is stored to the browser's local storage, a user can easily "break" the pixelise function by setting it to 1%.

Could there be a lower limit enforced so that pixelation always results in an obscurred image?

**Painterro version**

v1.2.41

**To Reproduce**
1. Go to 'settings'
2. Set "Pixelize pixel size" to 1%
3. Select a small area on an image
4. Click the "Pixelize selected area" button.

**Expected behavior**

Selected area of image should always be obscurred.

**Browser**

Google Chrome 89 on Windows

**Comment by ivictbor** [comment]
@appetere thanks a lot! I also think about it more and more, and definitely will fix it

**Comment by ivictbor** [comment]
@appetere Update to 1.2.45

And just use
```
pixelizeHideUserInput: true,
```

This will hide setting from dialog so users will be enforced to values defined by you in Painterro params.

**Comment by appetere** [comment]
Many thanks @ivictbor that's a nice simple way to avoid the problem.

**Comment by ivictbor** [comment]
@appetere Good, closing issue now, let us know if you need any help or have some issues
