### ISSUE TITLE
Paste image does not follow "how_to_paste_actions" option in empty background

### ISSUE THREAD

**Issue by losbit** [devforth/painterro#133]
Although It is expected behaviour, it’d be fine whether we paste or open image in empty background to follow “how_to_paste_actions” option set when we pass parameters to Painterro constructor.

For example: how_to_paste_actions: ['paste_over'],

It should always paste as "past_over" and not as "replace_all" as it is happening when paste in empty background

It is useful when we use background as a whole canvas to draw and paste on it even in empty background, it is a more natural behaviour. 

Thanks

**Comment by ivictbor** [comment]
@losbit done, please
```
npm i painterro@latest --save
```
and set a new param to `false` (it is true by default for backward compatibility):

```
replaceAllOnEmptyBackground: false,
```

**Comment by losbit** [comment]
Great!
Thanks!
