### ISSUE TITLE
[Bug] Text does not show when the background scrolls down

### ISSUE THREAD

**Issue by losbit** [devforth/painterro#137]
Whether the background is scrollable down, the Text does not show when applied, It only shows if the background is not scrolled down.

Occurs in all Painterro versions

![image](https://user-images.githubusercontent.com/45804465/116495992-aa78ad80-a869-11eb-8544-1d79c91bd112.png)
![image](https://user-images.githubusercontent.com/45804465/116496084-d6942e80-a869-11eb-9f6b-c67a52959510.png)
![image](https://user-images.githubusercontent.com/45804465/116496144-017e8280-a86a-11eb-83e3-a04fcc13c402.png)

If I continue scrolling down the text disappears

Occurs in all browsers and OSs

PD. It only occurs with Text Tool - (other tools work fine)
Toolbar position is at Top

**Comment by ivictbor** [comment]
@losbit how to achieves background scrollable down.  In which div? There might be thousands of scrollable options.

Please 
1. paste link to js fiddle which anyone can reproduce
2. Or attach code which 100% could be pasted to some page/devserver and reproduced


For now tried and can't reproduce

**Comment by losbit** [comment]
You can reproduce the bug in this link: http://junin.info/painterro.php
Notice that as the webpage body is bigger than Painterro's canvas, it is scrollable down, so once you scroll down Text does not work as expected.

**Comment by losbit** [comment]
https://user-images.githubusercontent.com/45804465/116639620-8d59e280-a92e-11eb-9a0f-e7f99ececb97.mp4

**Comment by ivictbor** [comment]
@losbit does it sound like related issue https://github.com/devforth/painterro/issues/90?

**Comment by losbit** [comment]
Wow @ivictbor Your are awesome!
Now Painterro is working fine.
Thanks,

**Comment by losbit** [comment]
Sorry @ivictbor but I found this:

If I set "position: fixed;" to the holder div, Text tool is not working as expected.

As previously, you can reproduce the bug in this link: http://junin.info/painterro.php

I'm using latest painterro version

https://user-images.githubusercontent.com/45804465/116769353-1a6d6c00-aa01-11eb-9dbd-dc826ad7910a.mp4

**Comment by ivictbor** [comment]
Yep, seams like fixed needs 0 scroll param in image2text setting I will try to discover their code to see how they detect compensation to apply insync anti- compensation

**Comment by ivictbor** [comment]
@losbit please try the latest release, for me works fine in both cases

**Comment by losbit** [comment]
@ivictbor 
Yes, It is working fine! -I really appreciate your help.
Thank you!
