### ISSUE TITLE
[Bug] Background resizes incorrectly in android

### ISSUE THREAD

**Issue by losbit** [devforth/painterro#139]
Description:
When Painterro is loaded in Android Chrome in portrait mode it works fine but when turned into landscape mode background resizes incorrectly.
![image](https://user-images.githubusercontent.com/45804465/116757856-88e80500-a9d4-11eb-9436-97b8259bff8e.png)
![image](https://user-images.githubusercontent.com/45804465/116757865-8edde600-a9d4-11eb-9c3f-b68b11cbe022.png)

Painterro version: latest version (all versions)

1. Open Chrome in Android 10 (portrait mode)
2. Load: http://junin.info/painterro.php
3. Change to landscape mode

**Comment by losbit** [comment]
https://user-images.githubusercontent.com/45804465/116759336-b3878d00-a9d7-11eb-992e-78e3f3fdd391.mp4

**Comment by losbit** [comment]
The same happens when we load Painterro in landscape mode then rotate to portrait mode:

https://user-images.githubusercontent.com/45804465/116759633-6657eb00-a9d8-11eb-9f80-91d7e48736fd.mp4

**Comment by ivictbor** [comment]
@losbit please clarify what do you mean by "incorrectly"?

As for me on all videos and images it does what it should, this was implemented from beginning, the image fit mode. Do you want cover mode or rotate image aria by 90 deg?

**Comment by ivictbor** [comment]
Closing because of luck explanation word "incorrectly", please feel free to reopen with clear explanation how you need it to behave
