### ISSUE TITLE
[Feature Request] Bucket Fill

### ISSUE THREAD

**Issue by bernd892374892** [devforth/painterro#140]
**Describe the feature**
Fills an area with a selected color. It's a very popular feature which painterro is lacking right now, unfortunately.

**Possible analogs?**
Gimp: https://docs.gimp.org/en/gimp-tool-bucket-fill.html

**Comment by ivictbor** [comment]
Hi @bernd892374892 , thanks, I will try to implement it as an additional tool so you will be able to enable it. As same-color detecting, it should work fine but in our world of compressed images/jpegs it might fill zones very ugly, hope you understand it. Or you will always need to find and true color thresholds if we will implement them (like in gimp).

BTW to do it I need to know your use-case. What is your web app about? Who is going to edit images and how? I mean e.g., can it bring practical adult value having a bucket fill? For example, for someone, it sounds like a tool for painters or kids. What would be your arguments?

**Comment by bernd892374892** [comment]
> Hi @bernd892374892 , thanks, I will try to implement it as an additional tool so you will be able to enable it. As same-color detecting, it should work fine but in our world of compressed images/jpegs it might fill zones very ugly, hope you understand it. Or you will always need to find and true color thresholds if we will implement them (like in gimp).

Thank you!

> BTW to do it I need to know your use-case. What is your web app about? Who is going to edit images and how? I mean e.g., can it bring practical adult value having a bucket fill? For example, for someone, it sounds like a tool for painters or kids. What would be your arguments?

It's an imageboard application. Users post a lot of images there, but they also discuss God and the world. Sometimes when they may not have an appropriate reaction image, they want to draw it directly on the site itself. Or other times they just want to draw stuff for the fun of it.

Here's an example: https://kohlchan.net/test/res/1064.html

We're using wPaint currently. It opens if you click on "size canvas".

**Comment by michaelklem** [comment]
I implemented a paint fill tool in an older version that I forked. I plan on updating to using the latest version of painterro and add my fill code as a PR.

My current code is [here](https://github.com/michaelklem/painterro/commits/master)

**Comment by ivictbor** [comment]
> I implemented a paint fill tool in an older version that I forked. I plan on updating to using the latest version of painterro and add my fill code as a PR.
> 
> My current code is [here](https://github.com/michaelklem/painterro/commits/master)

Thanks, will gladly merge

**Comment by ivictbor** [comment]
@michaelklem thanks a lot

@bernd892374892 available in 1.2.70, sensivity param could be tuned in library initialisation params, if you need a runtime input please let us know
