### ISSUE TITLE
Resize dialogue layout in Firefox

### ISSUE THREAD

**Issue by appetere** [devforth/painterro#141]
**Describe the bug**

The resize dialogue layout doesn't work correctly in Firefox v88.0 on Windows 10:

![image](https://user-images.githubusercontent.com/1777396/117682686-3b755000-b1ab-11eb-8519-a12ee6b745f4.png)

In Chrome v90.0 this is displayed as:

![image](https://user-images.githubusercontent.com/1777396/117682901-72e3fc80-b1ab-11eb-995b-c41455158d54.png)

**Painterro version**
1.2.41

**Comment by ivictbor** [comment]
@appetere thanks

**Comment by Darktimeoff** [comment]
@appetere thank you for the report, this issue was solved in the 1.2.56 version, please update painterro, `npm  i painterro@latest`
