### ISSUE TITLE
Tool tips missing for zoom buttons

### ISSUE THREAD

**Issue by appetere** [devforth/painterro#142]
**Describe the bug**

The tool-tips for the zoom buttons "-" and "+" show as "undefined" when you hover over them.

![image](https://user-images.githubusercontent.com/1777396/117683822-572d2600-b1ac-11eb-8d07-b2c069b7b0b4.png)

**Painterro version**
1.2.41

**To Reproduce**

Hover the mouse over one of the magnifying glass icons.

Tooltip appears with the word "undefined"

**Expected behavior**

Tool-tips like "Zoom in" and "Zoom out".

**Browser**
Chrome v90.0 on Windows

**Comment by ivictbor** [comment]
@appetere thanks

**Comment by Darktimeoff** [comment]
@appetere this issue was solved in 1.2.56 version painterro, please update painterro, to latest, using the command:  `npm i painterro@latest`
