### ISSUE TITLE
[Question] Could CanvasRecorder be used to record Painterro drawings?

### ISSUE THREAD

**Issue by mikben** [devforth/painterro#146]
Thanks for the wonderful library!

I'm playing with WebRTC CanvasRecorder, which records a `MediaStream` from a target `canvas` element: https://github.com/SMUsamaShah/CanvasRecorder

Would it be possible to use a `MediaRecorder` to record drawings made to the `canvas` element that painterro generates?

**Comment by ivictbor** [comment]
@mikben so basically you can get .canvas attribute of painterro, it is native canvas element, so just do what you want with it: get context or anything else:

```
ptro = Painterro();
ptro.canvas // <- this is a canvas
```
It is created from constructor and lives with Painterro instance.

So if it is possible to get MediaStream from the HTML canvas then it is possible to get MediaStream from Painterro.
