### ISSUE TITLE
getScale does not account for window.devicePixelRatio

### ISSUE THREAD

**Issue by jasonbarry** [devforth/painterro#147]
**Describe the bug**
html2canvas defaults to `window.devicePixelRatio` for the `scale` property ([docs](https://html2canvas.hertzen.com/configuration)), but [getScale](https://github.com/devforth/painterro/blob/fd402ff87016835ac59dc7820da49b42ad51e3f3/js/main.js#L1168) does not account for it. When `scale` is passed to html2canvas, it overwrites the default value. This results in a blurry canvas for Retina / 2x displays. 

**Painterro version**
v1.2.57

**Expected behavior**
I expect the arrows, text, lines, shapes, and other tools to not draw as blurry when using a Retina display. 

**Browser**
Chrome 91.0.4472.106 , Safari 14.1.1

**Comment by ivictbor** [comment]
Thanks a lot @jasonbarry . Just in case you need it urgently feel free to change that line of code and multiply by (window.devicePixelRatio || 1)

**Comment by jasonbarry** [comment]
Thanks for the quick response @ivictbor -- in my first tests, it looks like window.devicePixelRatio needs to be placed somewhere else so that it doesn't affect the rest of the coordinate system. I'll let you know if I find the right place to put it 👍

**Comment by IhorStorozhok** [comment]
Since version 1.2.64 html@canvas has been changed to dom-to-image.
