### ISSUE TITLE
Default tool gets selected instead of previously-used tool

### ISSUE THREAD

**Issue by jasonbarry** [devforth/painterro#149]
**Describe the bug**
In a few cases, the default tool gets selected when I expect the previously-used tool to remain selected. The cases are: 

- [ ] After under/redo
- [ ] After cropping
- [ ] After placing and confirming text on the canvas
- [ ] Clicking a tool that is already selected (aka clicking on the same tool twice in a row)

**Painterro version**
v1.2.57

**To Reproduce**
1. Define 'select' as your default tool
2. Draw something with the paint brush
3. Undo
4. Notice that 'select' is now the current tool, even though I was using brush 

![119550831-c9972c00-bd90-11eb-8449-67606c84aeb4](https://user-images.githubusercontent.com/236451/123999832-c989dd80-d987-11eb-8fc1-7ad53dbb0c67.gif)

**Expected behavior**
In these cases, I'd expect the previously used tool to remain selected, rather than selecting the default tool.

**Comment by ivictbor** [comment]
@jasonbarry fixed in 1.2.66, feel free to reopen if you will see any other issues with it
