### ISSUE TITLE
Zoom on mobile devices

### ISSUE THREAD

**Issue by MoritzGrossmann** [devforth/painterro#151]
If you zoom into the editor on a mobile device with your fingers, you have no chance to zoom out again. The editor zooms in further and further as you zoom out.

**Painterro version**
1.2.58

**To Reproduce**
1. Open Painterro Editor on a Mobile Device
2. Zoom with your fingers
3. Try to zoom out with your fingers

**Screenshots**
![painterro error 1](https://user-images.githubusercontent.com/26787611/126944914-72877b00-530b-43d3-9784-4aa7db20a735.PNG)

**Browser**
- Google Chrome 91 (Windows 10 on Mobile Device) 
- IOS Safari 12.1.2

**Comment by Senpai013045** [comment]
same issue with me

**Comment by jw7712** [comment]
I also have the same problem. I really like painterro, this is the only real issue i have with painterro atm.

**Comment by IhorStorozhok** [comment]
Has been fixed in release .82.
