### ISSUE TITLE
Move and resize shapes

### ISSUE THREAD

**Issue by hassanrashid725** [devforth/painterro#158]
Once we draw shapes in the Painterro, we should be able to move or resize them by using the select area tool.

The same functionality is being used in MS Paint.

**Example Using MS Paint**
Shapes drawn:
![image](https://user-images.githubusercontent.com/44922051/141273582-2f807949-261c-4aed-8fa8-8ba6c6a10b5b.png)

Shape selected with the select tool:
![image](https://user-images.githubusercontent.com/44922051/141273751-e5395068-be17-4444-8386-fe2de691921f.png)

Shape resized:
![image](https://user-images.githubusercontent.com/44922051/141273924-78895dc4-33c1-4a07-a812-c9ac66d02240.png)

Shape moved:
![image](https://user-images.githubusercontent.com/44922051/141274020-33e9b6ba-a558-4b4b-af43-2242c2db63f0.png)

Would you please add this functionality as it would be extremely useful? Thank you very much.

**Comment by hassanrashid725** [comment]
@ivictbor Hey. Can you please look into this? Please let me know if I can achieve this functionality somehow or if there are any plans for this feature in the near future. Thank you for this awesome library! :)

**Comment by ivictbor** [comment]
@hassanrashid725 
https://static.tracklify.com/live/attachments/NGDPrTu6HMR4SAV8EeekE/4oH1yt4FRgZoLsQ6AfJnHA/jABqQjejw7CzMFn8UxXAUX/vvwRnX8Ho5vdenKFbzbLd8.webm

**Comment by hassanrashid725** [comment]
Thank you so much! You're a lifesaver! 😃
