### ISSUE TITLE
can't save images

### ISSUE THREAD

**Issue by srt10coupe** [devforth/painterro#159]
**my config**

var ptro = Painterro({
                      id: 'pint',
                      saveHandler: function (image, done) {
                        var formData = new FormData();
                        formData.append('image', image.asBlob());
                        var xhr = new XMLHttpRequest();
                        xhr.open('POST', '../../assets/uploads/TP 100/ubernahme1.jpg', true);
                       xhr.onload = function () {
                         var response = JSON.parse(this.responseText);
                         console.log('Upload done:', response);
                        };
                        xhr.onerror = function (e) {
                            console.error('Error uploading image: ', e)
                            done(true)
                          };
                        xhr.send(formData);
                      }
                    })
                    ptro.show('../../assets/uploads/TP 100/ubernahme.jpg');

**Painterro version**
painterro-1.2.66

**Screenshots**
![screenshot_05](https://user-images.githubusercontent.com/399997/142777073-ca882a69-47f2-4f32-b55b-692cbc7f2762.png)

where is my mistake?

**Comment by ivictbor** [comment]
You serve returns non-JSON and you are trying to parse it as JSON

**Comment by srt10coupe** [comment]
Ok, how can I fix the error that I can save the image successfully?

**Comment by ivictbor** [comment]
From details that you provided : to fix red text in console don't use json parse function or make your backend  to return json. But it is not about saving at all. It is reading response from saving request.
Saving performed on backend in your case.

By your question I can see that you are at very beginning level, so I would recommend to find some very basic lessons about how to handle file uploading on backend, understand differences between multipart requests and urlencoded. Then read Readme section about saving carefully once again
