### ISSUE TITLE
[Firefox] Zoom with ctrl+moue wheel scroll doesn't work

### ISSUE THREAD

**Issue by krofinzki** [devforth/painterro#161]
**Describe the bug**
The default action in Firefox when using ctrl + mouse wheel scroll is to resize the entire page and that's what's happening here. Seems Firefox might need to check the DOMMouseScroll event instead of mousewheel event:
https://github.com/microsoft/monaco-editor/issues/1353#issuecomment-476683672

**How to reproduce**
1. Open Firefox and goto the live demo page
2. Hold down ctrl and use the mouse wheel to scroll

**Painterro version**
v1.2.66

**Browser**
Firefox only (works fine in Chrome and Edge)

**Comment by ivictbor** [comment]
@krofinzki PR is welcome
