### ISSUE TITLE
How to save image several times?

### ISSUE THREAD

**Issue by alex-webmaster** [devforth/painterro#162]
When the picture is saved, the animation remains on the save button and there is no way to save the image several times, for example, after modifying it. How to reset the save button to its default state to save the picture many times?

Thank you!

**Comment by ivictbor** [comment]
The animation disappeares when you call done callback (second parameter of save handler). Please read carefully https://github.com/devforth/painterro#saving-image-

**Comment by alex-webmaster** [comment]
Рlease add the same comment in all examples "//done(true) will hide painterro, done(false) will leave opened". 
Тhanks!
