### ISSUE TITLE
Color fill tool and trashcan tool

### ISSUE THREAD

**Issue by michaelklem** [devforth/painterro#164]
**Describe the feature**
Nice to have a way to perform color fills and erase the canvas quickly.

**Possible analogs?**
I added these to my pull request (https://github.com/devforth/painterro/pull/163)

I copied the color fill logic from a tutorial which I can no longer find.

**Comment by ivictbor** [comment]
@michaelklem thanks for a great job Michael!

Merged!
![MinionWoohooGIF](https://user-images.githubusercontent.com/1838656/145717196-8687c66b-2bc3-4d2a-8a33-e24cab0b6764.gif)
