### ISSUE TITLE
Demo isn't working

### ISSUE THREAD

**Issue by ospaarmann** [devforth/painterro#165]
Hey, after going to the [live demo](https://tracklify.com/painterro_demo/?next=/starting/%3Fpainterro) and clicking "sign up with Google" I received the error "Internal Server Error"

<img width="1523" alt="Screenshot 2022-01-05 at 17 11 13" src="https://user-images.githubusercontent.com/308086/148250330-fdf79b09-00cb-4f8c-b458-046dcb6ad53f.png">
.

**Comment by ivictbor** [comment]
Thanks will add fix

**Comment by ospaarmann** [comment]
It is working again. Thanks.
