### ISSUE TITLE
Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by kirti18patel** [devforth/painterro#166]
When I load painterro, I am getting runtime error indicating "Objects are not valid as a React child". When close this error it is working but encountering error first. Please share possible solution.

I am using 
    "painterro": "^1.2.70",
My editor component: 
```
import Painterro from 'painterro'
export default function Editor (src) {
  var ptro = Painterro({})
  return (
  <div>
  {
  ptro.show(src)}</div>
  );
};

```

Code for calling:
```
import dynamic from 'next/dynamic'
const DynamicComponentWithNoSSR = dynamic(
  () => import("../../components/editor"),
  {ssr : false}
)
const ProductList = withRouter((props) => {
return(
          <DynamicComponentWithNoSSR src={props.src}></DynamicComponentWithNoSSR>
)}
```
![Screenshot 2022-02-18 091407](https://user-images.githubusercontent.com/74840827/154702709-5976cdbe-aa69-46d9-93b3-5532a0ee9cfe.png)

**Comment by ivictbor** [comment]
Hi @kirti18patel ,
Please follow [minimal working Painterro in react demo demo](https://hinty.io/ivictbor/use-painterro-with-react/)
I've just wrote it for you
