### ISSUE TITLE
Working painterro in bootstrap modal window

### ISSUE THREAD

**Issue by dizelvis** [devforth/painterro#172]
Hello!
 I'm trying to place it in a bootstrap 4 modal but only getting the toolbar visible.
How I can do it?

Example: https://belov.tech/1.html
**Painterro version**
1.2.78

**Comment by dizelvis** [comment]
The image in the modal window is not visible until I zoom in or resize the window in the devtools. Why is that?

**Comment by dizelvis** [comment]
I found method adjustSizeFull()

**Comment by ivictbor** [comment]
I can't access example: DNS_PROBE_FINISHED_NXDOMAIN

Feel free to reopen the issue if it is still relevant.
