### ISSUE TITLE
Save image without background (using backplateImgUrl)

### ISSUE THREAD

**Issue by MathieuSollier** [devforth/painterro#175]
I use backplateImgUrl to put an image in the background to be able to draw on it. However, when I save, I only have my drawings WITHOUT the background.

**Painterro version**
E.g. v1.2.78

**Code**
Here is my code, for the moment I get the base64 from the saveHandler and I put it in an online viewer.

`    Painterro({
      id: "painterro",
      colorScheme: {
        main: '#fdf6b8', 
        control: '#FECF67',
      },
      backplateImgUrl: "data:" + selectedFile.file.mime_type + ';base64,' + selectedFile.data,
      toolbarPosition: "top",
      saveHandler: function (image, done) {
        console.log('done:', done)
        console.log(image.asDataURL())
      }
    }).show()`

**Screenshots**
What I drew :
![draw](https://user-images.githubusercontent.com/47887566/199919850-c7bdc261-bfa0-47d4-90bb-1ca0ed7a2c28.png)

What I saved:
![save](https://user-images.githubusercontent.com/47887566/199920040-d1a95a54-f93c-43ed-b34d-ef514a2326a5.png)

**Info**
Chrome Version 106.0.5249.61 
node : v14.0.0
npm : 6.14.4

Is there something I haven't seen?

Thank you in advance for your answer.

**Comment by ivictbor** [comment]
@MathieuSollier , this is the intended behavior of `backplateImgUrl` it should not be included in final image. It is pretty rare when you have to use this parameter, it was requested by community members who need to draw on top of something and save only what they added.

That is why it is called backplate!!!

![image](https://github.com/devforth/painterro/assets/1838656/a03d767a-e486-4852-b363-abb50d9761ef)

If you need save your background don't use `backplateImgURL` at all, just use `.show` API https://github.com/devforth/painterro?tab=readme-ov-file#api

You can pass URL as parameter and it will load image. If you have image in RAM already loaded without URL, just convert it to base64 and pass base64 URL

```
Painterro().show('URL of image to load')
```
