### ISSUE TITLE
Vite Build on Node 18 cannot initialize Painterro

### ISSUE THREAD

**Issue by ghost** [devforth/painterro#179]
**Describe the bug**
When attempting to use:
`import Painterro from 'painterro';
this.painterro= Painterro({
        id: 'painterro',
        toolbarPosition: 'top',
        });
`
**Painterro version**
1.2.78

**To Reproduce**
1. create a Vite app with Vue 2
2. import Painterro as in docs
3. initialize as in docs
4. run "npm run build" (or "vite build")
5. run "vite preview"
6. See error in browser

(it works when using development "vite" but fails after building for production with success)

![image](https://user-images.githubusercontent.com/57145364/207257852-ecf12870-68b9-4c5b-b5c5-3c0985e7d8df.png)

**Browser**
 - any browser

**Comment by renatovaler** [comment]
Any solution?

**Comment by mihaidgag** [comment]
> Any solution?

So, what I did, I took a pre-compiled version of painterro.js (one is available from a CDN on the repo's main page), I saved it in a folder called "utils" in my Vite project, then, where I needed it, I simply used an import as such:

`import Painterro from '../../utils/painterro';`

Then I could use everything Painterro related without problems. 
This is only a workaround is not by any means a solution.

**Comment by renatovaler** [comment]
I'm using Laravel 9 + Vue 3 + Vite.

This work for me:

import Painterro from 'painterro'

...

mounted() {
	this.painterro = Painterro.default({ id: 'painterro' })
}
...

methods: {
	showPainterro(imgSrc) {
		this.painterro.show(imgSrc)
	}
}
