### ISSUE TITLE
[Feature request] Toolbar zoom buttons

### ISSUE THREAD

**Issue by davesmith9088** [devforth/painterro#20]
It would be useful to add a zoom button on the toolbar that could allow zooming in and out of an image while keeping the toolbar etc fixed.

**Comment by ivictbor** [comment]
@davesmith9088 agree, thanks for the proposal

**Comment by maikl-plautech** [comment]
With the mouse wheel I can zoom in and out, it seems to work, the toolbar keep the same size.

**Comment by SamanKia** [comment]
Is zoom icon in toolbar coming soon? mouse wheel works but it'll change zoom of whole browser page (at least in chrome)

**Comment by ivictbor** [comment]
@SamanKia it was regression after some event fixes. Currently this bug was fixed, please upgrade to >=1.0.6!

**Comment by abelrgr** [comment]
Sorry guys but you have any news on this?

**Comment by ivictbor** [comment]
@abelrgr plant to work on it soon

**Comment by Darktimeoff** [comment]
@abelrgr, @SamanKia, @maikl-plautech, @davesmith9088 this features was added in version 1.2.36
