### ISSUE TITLE
[Feature Request] New positions

### ISSUE THREAD

**Issue by Leinad4Mind** [devforth/painterro#46]
Would be great to have the options at Right or Left side. Right now we can only choose between Top and Bottom for what I saw.

Best Regards

**Comment by ivictbor** [comment]
I think this should be done with next buttons set:

![image](https://user-images.githubusercontent.com/1838656/98681204-1a9e8000-236b-11eb-831c-4782ed613319.png)

**Comment by Leinad4Mind** [comment]
Seems good to me

**Comment by Darktimeoff** [comment]
@Leinad4Mind this option appeared in 1.2.9 version

**Comment by ivictbor** [comment]
Closing
