### ISSUE TITLE
Scale does not change size by ratio 

### ISSUE THREAD

**Issue by kingofnull** [devforth/painterro#69]
The scale button on resize options doesn't resize the canvas by given ratio it just set it by pixel.

**Comment by ivictbor** [comment]
Could you please provide more detailed steps to reproduce and result you see with screenshots. I can't reproduce

**Comment by kingofnull** [comment]
assume canvas size  100px X 100px :

![image](https://user-images.githubusercontent.com/11198668/66907057-936ec380-f015-11e9-977d-6d4973c9d8e4.png)

I scale it by factor of 2 in both directions:

![image](https://user-images.githubusercontent.com/11198668/66907209-d892f580-f015-11e9-850f-4f8fc9c4b41e.png)

I except the final resolution to be 200 x 200. But result is 2 x 2:

![image](https://user-images.githubusercontent.com/11198668/66908075-59062600-f017-11e9-89ee-92f520a5d446.png)

**Comment by ivictbor** [comment]
@kingofnull it is not factor, its distanation width and height in `px`

**Comment by ivictbor** [comment]
scale means that image will be scaled,
resize, that it will be extended to new size if size is grater by filling background with white or
reduced by cropping image, but elements will stay with same size.
Though agree, better name for resize might be `Extend/Reduce`

**Comment by kingofnull** [comment]
Ok got it sorry for misunderstanding.
