### ISSUE TITLE
直接加载线上图片报跨域错误

### ISSUE THREAD

**Issue by gaotaotao1213** [devforth/painterro#73]
Access to XMLHttpRequest at 'https://b-ssl.duitang.com/uploads/item/201808/19/20180819195241_yovmt.jpg' (redirected from 'http://b-ssl.duitang.com/uploads/item/201808/19/20180819195241_yovmt.jpg') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.能看看什么问题？解决一下吗？

**Comment by gaotaotao1213** [comment]
varimg =newImage();
img.setAttribute('crossOrigin','anonymous');--加这一行吧，我看源码没加
img.src = url;
是canvas图片跨域问题吧，得加一下这一行代码

**Comment by ivictbor** [comment]
Sorry, question is not clear
