### ISSUE TITLE
onbeforeunload

### ISSUE THREAD

**Issue by lukyer** [devforth/painterro#83]
Hello,

first of all thanks for this awesome lightweight image editor, it is the only one I found that suits my needs! I'm trying to integrate it with my project so I'm exploring its possibilities.

I'm missing onbeforeunload confirm option when some edit has been done but not saved. So I tried to implement it outside of this library. I came to this:

```   
$(window).on("beforeunload", function(e) {
        if (painterro.worklog.current.prevCount > 0) {
            return false;
        }
    });
```

It looks it is working however I'm not sure if it is reliable and it won't break something. \

Could you please confirm it? Or would you consider adding this option into library itself? It would be awesome.

Thanks!

**Comment by ivictbor** [comment]
@lukyer thank you for a interest and suggestion, implemented `onBeforeClose`, please check readme and update to latest version

**Comment by lukyer** [comment]
great, thanks! just note - README markdown looks corrupted since that change :)

**Comment by victor-schena** [comment]
Hi,
 So, I'm having the same issue, and I couldn't understand how to use onBeforeClose. Could you guys help me out?
