### ISSUE TITLE
Disable SAVE button

### ISSUE THREAD

**Issue by lukyer** [devforth/painterro#85]
Hello, 
could you please add disabling SAVE button until some edit is done? It would be more straightforward from UX perspective, some users were complaining :) I believe it is small change.

Thanks!

**Comment by theotimepoisseau-bib** [comment]
Hello,
Is adding `'save'` in `hiddenTools` array in config is sufficient for you ?

**Comment by lukyer** [comment]
Hello, it is not actually. Functionality I'm striving for is to have default SAVE button disabled (gray) until some painting is done by user. Only then it makes sense to enable SAVE button again.

I don't want to hide it, just to limit its functionality until it makes sense to actually save something.

Thanks!

**Comment by ivictbor** [comment]
@lukyer this behaviour was implemented a long time ago. WHich version do you use. You can check e.g. official demo https://maketips.net/paste

**Comment by lukyer** [comment]
I don't want to hide "save" tool, I just wanted to make it disabled until at least 1 edit is done by user. I hacked it by myself, so it's not important anymore :) thanks!
