### ISSUE TITLE
[Bug] Select default tool after cancel edition.

### ISSUE THREAD

**Issue by victor-schena** [devforth/painterro#87]
Hi,
First of all, thanks for sharing such an incredible tool, it's very easy and useful for both developers and end-users!
I don't know if this is really a bug, but, when I click in the close button, it shows up the modal I created on the method onBeforeClose, with the option for the user to close or cancel. 
When I click cancel,I hide my modal but the close button is kept "clicked", then I have to click in it twice, to try to close the editor again.

Is this possible to set the default tool again after canceling the close action?

Thanks in advance!

**Comment by victor-schena** [comment]
Just found out I could make a fake click on the $(".ptro-icon-close").parent().

**Comment by ivictbor** [comment]
@victor-schena nice touch
