### ISSUE TITLE
Setting className for SVG element raises error

### ISSUE THREAD

**Issue by pavitrakumar78** [devforth/painterro#88]
Hi,

I'm trying to integrate painterro with my web app, but when I try to draw a text, I get this error:

```
painterro-1.0.35.min.js:formatted:4682 Uncaught (in promise) TypeError: Cannot assign to read only property 'className' of object '#<SVGSVGElement>'
    at A.resolvePseudoContent (painterro-1.0.35.min.js:formatted:4682)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4609)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at A.cloneNode (painterro-1.0.35.min.js:formatted:4610)
    at new A (painterro-1.0.35.min.js:formatted:4506)
```

I looked around and found that this error comes from the html2canvas code. Issue raised here: https://github.com/niklasvh/html2canvas/issues/1868

This has been fixed by this pull request: https://github.com/niklasvh/html2canvas/pull/2034/files

I tried to reproduce this error in jsFiddle using the same painterro version I'm using, but I was not able to do it. I'm not sure why. For all my tests and development of my application, I'm using the latest Chrome browser and only in my application I'm seeing this error.

Please consider updating the html2canvas part of painterro so that future users can possibly avoid this error.

**Comment by ivictbor** [comment]
Hi @pavitrakumar78 thanks a lot for this report, I will bumb `html2canvas`

**Comment by pavitrakumar78** [comment]
Ah, yea. Looking at the last comment in that issue thread, they're still waiting for the maintainer to release it. I did manually patch the file for my dev purposes, but I'd probably keep this issue on hold/open incase any future devs have the same problem since the issue is with html2canvas's part. 

On a related note, I'm not sure why, but I can't get the text adding feature to work. Since it's a different problem, I've opened a new issue here:  https://github.com/devforth/painterro/issues/89
I'd appreciate it if you could take a look at it.
Thanks!

**Comment by mbaradza** [comment]
I was having the same issue and I reverted back to version 1.0.0-alpha.12 and it fixes my error

**Comment by ivictbor** [comment]
So now it is rc7 and hope it works for anyone. Please recreate issue if needed. Closing
