### ISSUE TITLE
text draw on image doesn't work if scroll position not zero

### ISSUE THREAD

**Issue by szabolcssimonyi** [devforth/painterro#90]
I realized a strange behaviour in this scenario:
My task is to show more images on a page, and if user clicks one of them painterro should show up and user can draw on selected image, than update image on the page when he/she closes the editor. 
However, in case scroll position of window is not zero, and paintero opened, text drawing isnt shown in the editor after apply button clicked it simply disappears. 
As a workaround, I can scroll to top position of the window in the onImageLoaded event handler, and disable scrolling for user, than reenable scrolling in onClose handler.
Other issue, that I cannot make .hide() function work, simply not able to close paintero programatically with it, however I was able to close it with $(".ptro-holder-wrapper").remove(); in saveHandler, which seems to be rather hacky...

**Comment by cherishang** [comment]
@szabolcssimonyi Hi, I am having the same issue here, Text disappears after clicking on the apply button. But how did you disable the scrolling? How to configure it in onImageLoaded event handler?

**Comment by szabolcssimonyi** [comment]
Hi
I'm not proud of it but I at the end I've done something like this:
```
function setImage() {
    lastScrollX = window.scrollX;
    lastScrollY = window.scrollY;
    window.scrollTo(0, 0);
    window.onscroll = function () {
        window.scrollTo(0, 0);
    };
    dirty = false;
}

var src = $(this).attr("src");
    currentImage = this;
    painterrow = Painterro({
        saveHandler: saveImage, onImageLoaded: setImage, onClose: setClose, onBeforeClose: beforeClose, onChange: changed,
        hiddenTools: ['open', 'rotate', 'resize', "arrow", "crop", "pixelize", "settings"],
        defaultTool: 'text',
        availableLineWidths: [1, 2, 4, 8, 10, 12, 16, 64],
        availableEraserWidths: [1, 2, 4, 8, 10, 12, 16, 64],
        availableFontSizes: [10, 11, 12, 13, 14, 15, 16, 20, 24, 28, 32, 64],
        hideByEsc: true
    });
    painterrow.show(src);

```

**Comment by cherishang** [comment]
@szabolcssimonyi thanks!

**Comment by ivictbor** [comment]
Hey guys, hope my team will find timeslot soon to work on it and make less hacky solutions

**Comment by ivictbor** [comment]
🎉🎉🎉 I want to end this painterro-fixes week with great news! The issue fixed.

Please:

```
npm i painterro@latest --save
```

It was in underlying `html2text` library which we use to rasterize the HTML which used in text input.
During rendering the added implicit offset based on window scroll, I was looking through doc and issues and found this: https://github.com/niklasvh/html2canvas/issues/1878#issuecomment-511678281
