### ISSUE TITLE
Set background image

### ISSUE THREAD

**Issue by steinm** [devforth/painterro#91]
Would it be possible to set a background image? The idea is to place an image in the background and paint on it, but only save what you have painted. The would enable to e.g. make notes on a file and store them separately.

**Comment by ivictbor** [comment]
@steinm this could be easily implemented with setting css properties to background:none of wrapping containers, but due to big likes count probably one day we will implement it in faster way

**Comment by gnawalishyam** [comment]
> @steinm this could be easily implemented with setting css properties to background:none of wrapping containers, but due to big likes count probably one day we will implement it in faster way

Will client be able to change this background if they want?

**Comment by ivictbor** [comment]
@Darktimeoff lets create some option called "backplateImage" where you can pass URL of backplate image which we will just load inside of div, if option is provided canvas should have full alpha channel so user can see the image

**Comment by Darktimeoff** [comment]
@gnawalishyam, @rayhaanq, @wolzenbug,@steinm this option appeared in the 1.2.5 version
