### ISSUE TITLE
Bug: The source width is 0

### ISSUE THREAD

**Issue by chniter** [devforth/painterro#92]
i have this bug when adding painterro inside bootstrap div:
![image](https://user-images.githubusercontent.com/2734864/79674057-e0f40500-81df-11ea-9d59-64525f217014.png)

**Comment by ivictbor** [comment]
@chniter please provide steps to reproduce, I've never seen this issue before

**Comment by chniter** [comment]
Hello

sorry for delay, the problem appear when i put the editor inside tab-content and tab-pan
` <div class="tab-content">
            <div id="painterro-editor" class="tab-pane" style="min-height:500px;width:500px;">
            </div>
        </div>`

**Comment by chniter** [comment]
main.size.h and main.size.w are equal to 0
That is why the editor not working correctly...

**Comment by chniter** [comment]
Finally, i know th real cause:
My tab is not shown on page load (because i have another active Tab) so the editor can't find real size.
So i will load The editor when tab becme active to avoid the problem.
