### ISSUE TITLE
[WordPress Plugin] Update the official WordPress plugin

### ISSUE THREAD

**Issue by alvarofranz** [devforth/painterro#98]
Painterro is a great software, congratulations and thank you for making it Open Source.

It may not be super famous but I have been looking around and can say it's the best of them all.

The [official WP plugin](https://wordpress.org/plugins/painterro/advanced/) has not been updated in 3 years already, it would be nice to do so.

I updated it locally with the latest minified Painterro JS (painterro-1.0.35) and it works like a charm on WP 5.4.2.

Also, it would be a good thing to:

- integrate it with the new Gutenberg editor.
- make the Painterro modal become fullscreen to make it feel more comfortable.

**If you need help with that**, count on me.

**Comment by ivictbor** [comment]
@alvarofranz thanks! fixed wp autorelease flow, it was broken
