### ISSUE TITLE
How to remove the gray border around the widget?

### ISSUE THREAD

**Issue by jeromechezpix** [devforth/painterro#99]
There is a quite large light gray border around the drawing widget by default (see Figure below). Since I'm using it in an embed fashion, I would like to remove this border. But I could not figure out how to do so through the configuration options. Is there an easy way to get rid of this gray border? Thanks a lot.

![image](https://user-images.githubusercontent.com/51781173/88922538-87848300-d270-11ea-84c5-9529d289a589.png)

**Comment by ivictbor** [comment]
@jeromechezpix it is box-shadow in ptro-holder class which appersa if you do not use `id` option. 
![image](https://user-images.githubusercontent.com/1838656/94523382-c071b180-0239-11eb-832e-0a884f0a7743.png)

You can just override it in your styles using 

```
.ptro-holder[class] {
    box-shadow: none;
}
```

Or just put painterro into some container with `id`

**Comment by jeromechezpix** [comment]
Thanks for the clues. It eventually worked with :
`.ptro-holder {
            top:0 !important;
            left:0 !important;
            bottom:0 !important;
            right:0 !important;
        }`
